# Generated by Django 5.2.6 on 2025-10-10 23:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre de la clínica')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('direccion', models.CharField(blank=True, max_length=256, null=True, verbose_name='Dirección de la clínica')),
                ('telefono', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo de contacto')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('MOROSO', 'Moroso'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20, verbose_name='Estado del grupo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_suspension', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de suspensión')),
            ],
            options={
                'verbose_name': 'Grupo (Clínica)',
                'verbose_name_plural': 'Grupos (Clínicas)',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('PACIENTE', 'Paciente'), ('MÉDICO', 'Médico'), ('ADMIN', 'Administrador'), ('RECEPCIONISTA', 'Recepcionista'), ('SUPER_ADMIN', 'Super Administrador')], max_length=64, unique=True, verbose_name='Nombre del rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='MENSUAL', max_length=20, verbose_name='Tipo de pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto a pagar')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('fecha_vencimiento', models.DateTimeField(verbose_name='Fecha de vencimiento')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado del pago')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción o notas')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='cuentas.grupo', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre completo')),
                ('password', models.CharField(max_length=128)),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Género')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('telefono', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=256, null=True, verbose_name='Dirección')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('estado', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('ultimo_login', models.DateTimeField(auto_now=True, verbose_name='Último ingreso')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='cuentas.grupo', verbose_name='Grupo al que pertenece')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='cuentas.rol', verbose_name='Rol del usuario')),
            ],
            options={
                'verbose_name': 'Usuario del sistema',
                'verbose_name_plural': 'Usuarios del sistema',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.TextField(help_text="Descripción legible de la acción (ej: 'médico Pedro eliminó al paciente Juanito')")),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('objeto', models.CharField(blank=True, help_text="Texto corto indicando el objeto afectado (ej: 'Paciente: Juanito (id:4)')", max_length=200, null=True)),
                ('extra', models.JSONField(blank=True, help_text='Información adicional en JSON (opcional)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='cuentas.grupo', verbose_name='Grupo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to='cuentas.usuario')),
            ],
            options={
                'verbose_name': 'Registro de bitácora',
                'verbose_name_plural': 'Bitácoras',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['correo'], name='cuentas_usu_correo_6e6f28_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol', 'estado'], name='cuentas_usu_rol_id_4bab0d_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['grupo', 'estado'], name='cuentas_usu_grupo_i_ba4ae2_idx'),
        ),
    ]
