# Generated by Django 5.2.6 on 2025-10-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(choices=[('paciente', 'Paciente'), ('medico', 'Médico'), ('administrador', 'Administrador'), ('superAdmin', 'Super Administrador')], max_length=64, unique=True, verbose_name='Nombre del rol'),
        ),
    ]
