# Generated by Django 5.2.6 on 2025-10-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_alter_rol_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token_reset_password',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
