# Generated by Django 5.2.6 on 2025-11-22 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0003_usuario_token_reset_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_usuarios', models.IntegerField(default=5)),
                ('limite_almacenamiento_gb', models.IntegerField(default=1)),
                ('soporte_prioritario', models.BooleanField(default=False)),
                ('reportes', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada'), ('PENDIENTE', 'Pendiente de Pago')], default='PENDIENTE', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField()),
                ('renovacion_automatica', models.BooleanField(default=True)),
                ('id_suscripcion_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion_info', to='cuentas.grupo')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suscripciones.plan')),
            ],
        ),
        migrations.CreateModel(
            name='PagoSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('referencia_pago', models.CharField(max_length=100)),
                ('exitoso', models.BooleanField(default=True)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_pagos', to='suscripciones.suscripcion')),
            ],
        ),
    ]
