# Generated by Django 5.2.6 on 2025-10-12 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0002_alter_rol_nombre'),
        ('doctores', '0001_initial'),
        ('historiasDiagnosticos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita_Medica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha de la cita médica')),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio de la cita médica')),
                ('hora_fin', models.TimeField(help_text='Hora de fin de la cita médica')),
                ('estado', models.BooleanField(default=True, help_text='Activo = True, Cancelado = False')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre la cita médica')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('motivo_cancelacion', models.TextField(blank=True, help_text='Motivo de la cancelación, si aplica ')),
                ('bloque_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='doctores.bloque_horario')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_medicas', to='cuentas.grupo', verbose_name='Grupo al que pertenece')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='historiasDiagnosticos.paciente')),
            ],
            options={
                'verbose_name': 'Cita Médica',
                'verbose_name_plural': 'Citas Médicas',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['fecha_creacion'], name='citas_pagos_fecha_c_a2d14a_idx'), models.Index(fields=['estado'], name='citas_pagos_estado_b46f7a_idx')],
            },
        ),
    ]
