# Generated by Django 5.2.6 on 2025-10-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_pagos', '0001_initial'),
        ('cuentas', '0003_usuario_token_reset_password'),
        ('doctores', '0001_initial'),
        ('historiasDiagnosticos', '0002_tratamientomedicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita_medica',
            name='estado_cita',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No Asistió')], default='PENDIENTE', help_text='Estado actual de la cita', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita_medica',
            name='estado',
            field=models.BooleanField(default=True, help_text='Activo = True, Eliminado = False'),
        ),
        migrations.AlterField(
            model_name='cita_medica',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, help_text='Motivo de la cancelación, si aplica'),
        ),
        migrations.AddIndex(
            model_name='cita_medica',
            index=models.Index(fields=['estado_cita'], name='citas_pagos_estado__f932df_idx'),
        ),
    ]
