# Generated by Django 5.2.6 on 2025-10-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_pagos', '0002_cita_medica_estado_cita_alter_cita_medica_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita_medica',
            name='calificacion',
            field=models.IntegerField(blank=True, help_text='Calificación de la cita médica (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='cita_medica',
            name='comentario_calificacion',
            field=models.TextField(blank=True, help_text='Comentario sobre la calificación, si aplica'),
        ),
    ]
