# Generated by Django 5.2.6 on 2025-10-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_pagos', '0003_cita_medica_calificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita_medica',
            name='reporte',
            field=models.TextField(blank=True, null=True),
        ),
    ]
