# Generated by Django 5.2.6 on 2025-11-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_pagos', '0004_cita_medica_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita_medica',
            name='tipo',
            field=models.CharField(choices=[('CONSULTA', 'Consulta'), ('EMERGENCIA', 'Emergencia'), ('CONTROL', 'Control'), ('OTRO', 'Otro')], default='CONSULTA', help_text='Tipo de cita médica', max_length=30),
        ),
    ]
