# Generated by Django 5.2.6 on 2025-10-11 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0002_alter_rol_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatologiasO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre oficial de la patología', max_length=120, unique=True)),
                ('alias', models.CharField(blank=True, help_text='Alias o nombres comunes de la patología', max_length=120)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la patología')),
                ('gravedad', models.CharField(choices=[('LEVE', 'Leve'), ('MODERADA', 'Moderada'), ('GRAVE', 'Grave'), ('CRITICA', 'Critica')], max_length=50)),
                ('estado', models.BooleanField(default=True, help_text='Activo = True, Eliminado = False')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(help_text='Patología pertenece a este grupo/clínica', on_delete=django.db.models.deletion.CASCADE, related_name='patologias', to='cuentas.grupo', verbose_name='Grupo al que pertenece')),
            ],
            options={
                'verbose_name': 'Patologia',
                'verbose_name_plural': 'Patologias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_historia_clinica', models.CharField(help_text='Ejemplo: HC-2023-0001', max_length=64, unique=True)),
                ('agudeza_visual_derecho', models.CharField(blank=True, help_text='Ejemplo: 20/20', max_length=20)),
                ('agudeza_visual_izquierdo', models.CharField(blank=True, help_text='Ejemplo: 20/20', max_length=20)),
                ('presion_ocular_derecho', models.DecimalField(blank=True, decimal_places=2, help_text='Ejemplo: 15.50', max_digits=5, null=True)),
                ('presion_ocular_izquierdo', models.DecimalField(blank=True, decimal_places=2, help_text='Ejemplo: 15.50', max_digits=5, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cuentas.usuario')),
                ('patologias', models.ManyToManyField(blank=True, related_name='pacientes', to='historiasDiagnosticos.patologiaso')),
            ],
            options={
                'ordering': ['usuario'],
            },
        ),
        migrations.AddIndex(
            model_name='patologiaso',
            index=models.Index(fields=['nombre'], name='historiasDi_nombre_c180d0_idx'),
        ),
        migrations.AddIndex(
            model_name='patologiaso',
            index=models.Index(fields=['gravedad'], name='historiasDi_graveda_f064bf_idx'),
        ),
        migrations.AddIndex(
            model_name='patologiaso',
            index=models.Index(fields=['grupo'], name='historiasDi_grupo_i_71ecf5_idx'),
        ),
    ]
