# Generated by Django 5.2.6 on 2025-10-12 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_usuario_token_reset_password'),
        ('historiasDiagnosticos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TratamientoMedicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre oficial del tratamiento', max_length=120)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del tratamiento', null=True)),
                ('duracion_dias', models.PositiveIntegerField(blank=True, help_text='Duración del tratamiento en días', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(help_text='Tratamiento pertenece a este grupo/clínica', on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='cuentas.grupo', verbose_name='Grupo al que pertenece')),
                ('patologias', models.ManyToManyField(blank=True, related_name='tratamientos', to='historiasDiagnosticos.patologiaso')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='historiasDi_nombre_ee94a4_idx'), models.Index(fields=['grupo'], name='historiasDi_grupo_i_dd4ccd_idx')],
            },
        ),
    ]
