# Generated by Django 5.2.6 on 2025-10-30 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_pagos', '0004_cita_medica_reporte'),
        ('doctores', '0001_initial'),
        ('historiasDiagnosticos', '0002_tratamientomedicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoExamenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_examen', models.CharField(choices=[('topografia_corneal', 'Topografía Corneal'), ('oct_retina', 'OCT de Retina'), ('oct_nervio_optico', 'OCT de Nervio Óptico'), ('foto_anterior', 'Fotografía Segmento Anterior'), ('foto_anexos', 'Fotografía de Anexos'), ('microscopia', 'Microscopía Especular'), ('otro', 'Otro')], help_text='Tipo de examen (ej: OCT, fondo de ojo, etc.)', max_length=120)),
                ('archivo_url', models.CharField(help_text='URL o ruta del archivo', max_length=255)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del médico')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REVISADO', 'Revisado'), ('ARCHIVADO', 'Archivado')], default='PENDIENTE', help_text='Estado del resultado', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cita_medica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_examenes', to='citas_pagos.cita_medica')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_examenes', to='doctores.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_examenes', to='historiasDiagnosticos.paciente')),
            ],
            options={
                'verbose_name': 'Resultado de Examen',
                'verbose_name_plural': 'Resultados de Exámenes',
                'ordering': ['-fecha_creacion', '-fecha_actualizacion'],
            },
        ),
    ]
