# Generated by Django 5.2.6 on 2025-11-01 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_usuario_token_reset_password'),
        ('historiasDiagnosticos', '0003_resultadoexamenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoexamenes',
            name='grupo',
            field=models.ForeignKey(blank=True, help_text='Resultado de examen pertenece a este grupo/clínica', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados_examenes', to='cuentas.grupo', verbose_name='Grupo al que pertenece'),
        ),
    ]
