# Generated by Django 5.2.6 on 2025-11-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiasDiagnosticos', '0004_resultadoexamenes_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoexamenes',
            name='archivo_url',
            field=models.CharField(blank=True, help_text='URL o ruta del archivo', max_length=255, null=True),
        ),
    ]
