# Generated by Django 5.2.6 on 2025-11-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiasDiagnosticos', '0005_alter_resultadoexamenes_archivo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoexamenes',
            name='tipo_examen',
            field=models.CharField(choices=[('Topografía Corneal', 'Topografía Corneal'), ('OCT de Retina', 'OCT de Retina'), ('OCT de Nervio Óptico', 'OCT de Nervio Óptico'), ('Fotografía Segmento Anterior', 'Fotografía Segmento Anterior'), ('Fotografía de Anexos', 'Fotografía de Anexos'), ('Microscopía Especular', 'Microscopía Especular'), ('Otro', 'Otro')], help_text='Tipo de examen (ej: OCT, fondo de ojo, etc.)', max_length=120),
        ),
    ]
