# Generated by Django 5.2.6 on 2025-11-01 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historiasDiagnosticos', '0006_alter_resultadoexamenes_tipo_examen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadoexamenes',
            name='cita_medica',
        ),
    ]
