# Generated by Django 5.2.6 on 2025-11-22 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimEspecialidad',
            fields=[
                ('especialidad_key', models.AutoField(primary_key=True, serialize=False)),
                ('id_especialidad_sistema', models.IntegerField()),
                ('nombre_especialidad', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dim_especialidad',
            },
        ),
        migrations.CreateModel(
            name='DimEstadoCita',
            fields=[
                ('estado_key', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_estado', models.CharField(max_length=50)),
                ('descripcion_estado', models.CharField(max_length=100)),
                ('es_cancelacion', models.BooleanField(default=False)),
                ('es_asistencia', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'dim_estado_cita',
            },
        ),
        migrations.CreateModel(
            name='DimMedico',
            fields=[
                ('medico_key', models.AutoField(primary_key=True, serialize=False)),
                ('id_medico_sistema', models.IntegerField()),
                ('nombre_completo', models.CharField(max_length=200)),
                ('numero_colegiado', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=1, null=True)),
                ('fecha_registro', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'dim_medico',
            },
        ),
        migrations.CreateModel(
            name='DimPaciente',
            fields=[
                ('paciente_key', models.AutoField(primary_key=True, serialize=False)),
                ('id_paciente_sistema', models.IntegerField()),
                ('numero_historia_clinica', models.CharField(max_length=50)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=1, null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('grupo_etario', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'dim_paciente',
            },
        ),
        migrations.CreateModel(
            name='DimTiempo',
            fields=[
                ('fecha_key', models.IntegerField(help_text='Formato YYYYMMDD', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('anio', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('trimestre', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('nombre_mes', models.CharField(max_length=20)),
                ('dia', models.IntegerField()),
                ('dia_semana', models.IntegerField()),
                ('nombre_dia', models.CharField(max_length=20)),
                ('es_fin_de_semana', models.BooleanField()),
            ],
            options={
                'db_table': 'dim_tiempo',
            },
        ),
        migrations.CreateModel(
            name='FactCitas',
            fields=[
                ('cita_key', models.AutoField(primary_key=True, serialize=False)),
                ('id_cita_sistema', models.BigIntegerField()),
                ('hora_inicio', models.TimeField(null=True)),
                ('cantidad_citas', models.IntegerField(default=1)),
                ('duracion_minutos', models.IntegerField(null=True)),
                ('tiempo_anticipacion_dias', models.IntegerField(null=True)),
                ('especialidad', models.ForeignKey(db_column='especialidad_key', on_delete=django.db.models.deletion.CASCADE, to='business_intelligence.dimespecialidad')),
                ('estado', models.ForeignKey(db_column='estado_key', on_delete=django.db.models.deletion.CASCADE, to='business_intelligence.dimestadocita')),
                ('fecha_cita', models.ForeignKey(db_column='fecha_cita_key', on_delete=django.db.models.deletion.CASCADE, to='business_intelligence.dimtiempo')),
                ('medico', models.ForeignKey(db_column='medico_key', on_delete=django.db.models.deletion.CASCADE, to='business_intelligence.dimmedico')),
                ('paciente', models.ForeignKey(db_column='paciente_key', on_delete=django.db.models.deletion.CASCADE, to='business_intelligence.dimpaciente')),
            ],
            options={
                'db_table': 'fact_citas',
            },
        ),
    ]
