# Generated by Django 5.2.6 on 2025-11-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factcitas',
            name='grupo_id',
            field=models.IntegerField(db_index=True, default=1, help_text='ID de la Clínica (Tenant)'),
        ),
        migrations.AddIndex(
            model_name='factcitas',
            index=models.Index(fields=['grupo_id', 'fecha_cita'], name='fact_citas_grupo_i_f860a5_idx'),
        ),
    ]
